### PR TITLE
fix: Add missing error message when an error occurred

### LINKED ISSUE #255: [BUG] Missing error message when unknown exception is thrown
### Observed behavior

Before the version v1.5.0 when we were receiving a `GENERAL` error we had the error message associated to the error.

Since the v1.5.0 we are not receiving the error message anymore.

### Expected Behavior

Receive the error message associated with the error.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by thomaspoignant**
## This PR
- Add missing error message when an error occurred

### Related Issues
Fixes #255

### CODE REVIEW

**Review by kinyoklion — APPROVED** [review]
Code coverage issue seems unrelated to this. 

Change looks good.

**Comment by thomaspoignant** [comment]
> It would be nice to have a unit test for this condition.

I haven't worked on the SDK, and my knowledge of dotnet is limited so not sure how to trigger the exception in the test.
Any help is welcome.

**Comment by kinyoklion** [comment]
> > It would be nice to have a unit test for this condition.
> 
> I haven't worked on the SDK, and my knowledge of dotnet is limited so not sure how to trigger the exception in the test. Any help is welcome.

Let me take a look.

File: src/OpenFeature/OpenFeatureClient.cs [hunk 1]
```diff
@@ -262,7 +262,7 @@ public void AddHooks(IEnumerable<Hook> hooks)
             {
                 this._logger.LogError(ex, "Error while evaluating flag {FlagKey}", flagKey);
                 var errorCode = ex is InvalidCastException ? ErrorType.TypeMismatch : ErrorType.General;
```
Comment (kinyoklion) [inline src/OpenFeature/OpenFeatureClient.cs:264]: It looks like this line helps find how we could test this.

There is a test `OpenFeatureClient_Should_Return_DefaultValue_When_Type_Mismatch` which triggers this condition, and now it will have a message. 

```
            var evaluationDetails = await client.GetObjectDetails(flagName, defaultValue);
            evaluationDetails.ErrorMessage.Should().Be(new InvalidCastException().Message);
```

Comment (thomaspoignant) [reply src/OpenFeature/OpenFeatureClient.cs:264]: Oh, thanks it works 🙌 

Coverage is still not working, but it is not related to anything introduced by this PR.

**Review by askpt — APPROVED** [review]
LGTM. Is the coverage not working because of a missing token? I thought that if we kept the v3, it would never require 🤔

**Review by benjiro — APPROVED** [review]
