### PR TITLE
fix: Refactor error handling and improve documentation

### LINKED ISSUE #416: [FEATURE] Make error log for flag not found optionally a warning/disabled
### Requirements

Feature flags may not exist in production environments prior to CI/CD deployments.
The task of adding feature flags for us is tracked via external tools so an error log entry is needless and clogs our log monitors giving false positives, so a warning would be a sufficient level in this case.

It might even be nice to have the level entirely configurable for flag not found or disable it entirely.

### PR DESCRIPTION
**Pull request by askpt**
Signed-off-by: André Silva <2493377+askpt@users.noreply.github.com>

## This PR

This pull request includes updates to the `README.md`, changes to error handling in `OpenFeatureClient`, and improvements to the `InMemoryProvider` and its related tests.

Documentation updates:

* Added notes and examples to the `README.md` to improve clarity on logging, transaction context propagators, dependency injection, and custom providers. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R4) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R157) [[4]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R170) [[5]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R266) [[6]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R276) [[7]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R360-R378) [[8]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R387-R390) [[9]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R406) [[10]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R450) [[11]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R469)

Error handling improvements:

* Removed redundant error logging methods `FlagEvaluationError` and `FlagEvaluationErrorWithDescription` in `OpenFeatureClient`. [[1]](diffhunk://#diff-c23c8a3ea4538fbdcf6b1cf93ea3de456906e4d267fc4b2ba3f8b1cb186a7907L279) [[2]](diffhunk://#diff-c23c8a3ea4538fbdcf6b1cf93ea3de456906e4d267fc4b2ba3f8b1cb186a7907L293) [[3]](diffhunk://#diff-c23c8a3ea4538fbdcf6b1cf93ea3de456906e4d267fc4b2ba3f8b1cb186a7907L400-L402)

InMemoryProvider enhancements:

* Changed `InMemoryProvider` to return `ResolutionDetails` with appropriate error types instead of throwing exceptions for missing flags or type mismatches. [[1]](diffhunk://#diff-4734ad108181b3c0b9f2c89e921b023e0d3e06d3c26ba1bed6352a75643469b0L106-R105) [[2]](diffhunk://#diff-4734ad108181b3c0b9f2c89e921b023e0d3e06d3c26ba1bed6352a75643469b0L116-R115)

Test updates:

* Updated tests in `OpenFeatureClientTests` and `InMemoryProviderTests` to reflect changes in error handling and ensure proper error types and reasons are returned. [[1]](diffhunk://#diff-97c93c206b866c1293c8c476783ad62d653cbac48716afc15d418b7701431e30L187-R187) [[2]](diffhunk://#diff-9cc800e07a869b42598d8f63786c01c406128056e28c995e73b13f229d9c912fL178-R185) [[3]](diffhunk://#diff-9cc800e07a869b42598d8f63786c01c406128056e28c995e73b13f229d9c912fL233-R242)

Configuration changes:

* Modified `global.json` to update the SDK roll-forward policy from `latestMajor` to `latestFeature`.

### Related Issues

Fixes #416

### Notes
After evaluating the `global.json`, I noticed the [rollForward](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#rollforward) was way too high for what we should be using. I reduced to `latestFeature` which is safer and would allow us to change the GitHub Actions to use the version from `global.json` instead of from declaring it in the action itself.

### CODE REVIEW

File: src/OpenFeature/Providers/Memory/InMemoryProvider.cs [hunk 1]
```diff
@@ -103,7 +102,7 @@ private ResolutionDetails<T> Resolve<T>(string flagKey, T defaultValue, Evaluati
         {
             if (!this._flags.TryGetValue(flagKey, out var flag))
             {
-                throw new FlagNotFoundException($"flag {flagKey} not found");
+                return new ResolutionDetails<T>(flagKey, defaultValue, ErrorType.FlagNotFound, Reason.Error);
```
Comment (askpt) [inline src/OpenFeature/Providers/Memory/InMemoryProvider.cs:105]: I changed this reference to not throw an exception but return `FlagNotFound`. Please let me know if we want to change this behaviour.

File: README.md [hunk 2]
```diff
@@ -152,6 +154,7 @@ var value = await client.GetBooleanValueAsync("boolFlag", false, context, new Fl
 ### Logging
 
 The .NET SDK uses Microsoft.Extensions.Logging. See the [manual](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line) for complete documentation.
+Note that in accordance with the OpenFeature specification, the SDK doesn't generally log messages during flag evaluation.
```
Comment (beeme1mr) [inline README.md:157]: You could tease the logging hook here if it's available.

File: src/OpenFeature/Providers/Memory/InMemoryProvider.cs (hunk 1 above)
Comment (beeme1mr) [reply src/OpenFeature/Providers/Memory/InMemoryProvider.cs:105]: Yes, it's better to avoid throwing is possible but please ensure the error hook is still run when the flag isn't found.

Comment (askpt) [reply src/OpenFeature/Providers/Memory/InMemoryProvider.cs:105]: I just rechecked the code execution. When the evaluation returns an Error, it will always call the hook. Check https://github.com/open-feature/dotnet-sdk/blob/c9e5ded5a36b3130b2743c75f408ffbfa5842edd/src/OpenFeature/OpenFeatureClient.cs#L279

**Review by kriscoleman — APPROVED** [review]
changes look good to me 

I agree with the change on the flag-not-found. I prefer not to use exceptions to control logic flow; that's an old anti-pattern, and those stack traces have a hidden cost. 

Thanks! 

:shipit:

**Review by weyert — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]
